import { createSlice } from '@reduxjs/toolkit';
export const userSlice = createSlice({
  name: 'users',
  initialState: [],
  reducers: {
    // Add a new user
    addUser: (state, action) => {
      state.push(action.payload);
    },
    // Remove a user by ID
    removeUser: (state, action) => {
      return state.filter(user => user.id !== action.payload.id);
    },
    // Update a user's details by ID
    updateUser: (state, action) => {
      const index = state.findIndex(user => user.id === action.payload.id);
      if (index !== -1) {
        state[index] = action.payload; // Replace the old user data with the new one
      }
    },
    userLogout:(state)=>{
      state=[]
    }
  },
});

// Export actions generated by the slice
export const { addUser, removeUser, updateUser } = userSlice.actions;

// Export the reducer to be used in the store
export default userSlice.reducer;